### PR TITLE
Better error for GeometryCollection input. Fixes #172

### LINKED ISSUE #172: Add support for GeometryCollections
https://github.com/mapbox/cardboard/blob/master/lib/utils.js#L82-L83 stops `GeometryCollections` from being saved. What is the reason behind not saving these?

### PR DESCRIPTION
**Pull request by tmcw**
cc @mcwhittemore or @rclark for the review

### CODE REVIEW

**Comment by mcwhittemore** [comment]
@tmcw this looks good to me.

**Comment by mcwhittemore** [comment]
Meh. This is a breaking change if users were expecting that error message.  @rclark thoughts? Should I bug bump or major bump?

**Comment by rclark** [comment]
Might as well be honest and call it a breaking change.

**Comment by mcwhittemore** [comment]
Cool. Changelog updated and cardboard published.

**Pull request merged**
