### PR TITLE
API Documentation

### LINKED ISSUE #123: Generated documentation with dox and doxme

### PR DESCRIPTION
**Pull request by rclark**
An attempt to implement API documentation via [documentation-js](http://documentationjs.github.io/).

I'm not super happy with how the HTML docs ended up in terms of structure and making relationships to the code clear. Hoping @tmcw might have some pointers for using documentation-js more effectively? 

Some specific questions I had:
- what's the best way to document factories + module-pattern JS libs?
- what to do about nesting in the cardboard object?

  ```js
  cardboard.put = function(feature, dataset, callback) { ... };
  cardboard.batch.put = function(featureCollection, dataset, callback) { ... };
  ```

- how do you document parameters that expect configuration objects, and document the required/optional properties of those objects?
- how to document what will be given to a callback function?

This also prompts me to think more deeply about the structure of the cardboard client, and what I'd like to refactor / remove. @willwhite @mick I was hoping you could take a minute to look over https://gist.github.com/rclark/1af535d33d9f24f75a7c and see what you think of the structure kicking around in my head?

Fixes #123

### CODE REVIEW

**Comment by mick** [comment]
Re: [refactor gist](https://gist.github.com/rclark/1af535d33d9f24f75a7c)

I dont think we should do `.use`. Unlike a database, the dataset your are working with changes often (every request for us in most cases) So I think this would just be one more way of getting in trouble

Why the move to `.batch` and `.dataset` rather then `.listDatasets()` etc?  I like dyno or aws-sdk single object for all functions. I dont think we have enough that we need that much hierarchy in the namespace, imho.

+1 for remove `.dump` and `.export`.  I think we should remove listDatasets as well. Its scans the whole table, so unless we implement it another way that function is a trap.

+1 to `.list()` returning a stream if no callback.

**Comment by willwhite** [comment]
^ :+1: 

I would still sort of like to see a single function for bulk updates, just like we see with DynamoDB. I think there is a strong use case for making updates and deletes in the same request.

**Comment by rclark** [comment]
> I dont think we should do .use

Yeah I mostly agree. I think in service-type libraries using cardboard, `dataset` will vary a lot and there's no need for this. In some other application you might be repeatedly acting on a single dataset, as though it were a database within your layer. As we don't have an obvious use for it now, I won't go there.

> I like dyno or aws-sdk single object for all functions

Lumpers vs. splitters. I tend to fall on the splitter side. Honestly in this case I don't know of any meaningful reasons to swing one way or another. Got any? I am swingable.

> I would still sort of like to see a single function for bulk updates

While I can see places that it'd be advantageous, my gut tends to go :-1: to this because of how far it departs from my concept of resource-oriented apis. When batch and put are separate, you clearly identify a set of resources, and you have functions that take a specific action on those resources. With a combined batch write your request needs to include not only resource identification, but also a description of what action to take on those resources. As usual, I am swingable.

**Comment by rclark** [comment]
Ok so I've written a lot of JSDoc comments now, and you can build the documentation with an `npm run-script docs`, which is nice. Every function has *something* written about it and there are examples for the most pertinent things. However the biggest problem I have with the auto-generated documentation is the ordering of things. Apparently I am not alone: https://github.com/documentationjs/documentation/issues/100.

- [Auto-generated markdown](https://github.com/mapbox/cardboard/blob/bd91103dc02c9a240b166fdb23b625a253da38af/api.md) puts the functions in alphabetical order without any respect for which "class" they belong to. The resulting doc is not very helpful because of this.

- In the HTML docs the order in which "class" members are listed is alphabetical, but it would be really nice to be able to force a non-alphanumeric order that helps spell out the API in a more fluid fashion.

- There's no really great way to document callback functions. I can document callback functions by forcing [the JSDoc recipe to work](http://usejsdoc.org/tags-param.html#callback-functions), but the documentation for the callback function cannot be "grouped" with the method to which is pertains.

Solving these problems probably means digging in deeper on [documentation-js](https://github.com/documentationjs/documentation/issues).

**Comment by rclark** [comment]
[Better sorting in documentation-js](https://github.com/documentationjs/documentation/pull/105) is an ongoing thing that I'm struggling to find the time to pin down. For now I need to not let it block the next cardboard release.

So this PR adds a `npm run-script docs` command that'll update an `api.md` document that isn't perfect, but is better than where we were and can be iterated on.

**Pull request merged**
