### PR TITLE
track number of edits in a datasets metadata

### LINKED ISSUE #160: Store number of edits in the metadata
A count of the number of edits would be helpful when trying to decide if you need to do a large recalculation of something derived from datasets stored in cardboard. While this won't keep copies of different versions of the dataset it will let users know if their derivative of the data is behind the data itself and will also let developers know if one derivative is from newer data than another one. 

To do this I think we'd just want to update [metadata.adjustProperties](https://github.com/mapbox/cardboard/blob/1d1238b736ab63e3433df902d11234169a05d1a9/lib/metadata.js#L160) and [metadata.defaultInfo](https://github.com/mapbox/cardboard/blob/1d1238b736ab63e3433df902d11234169a05d1a9/lib/metadata.js#L73)

I'm not 100% sure how dynamo works with add on properties that haven't been created yet, so this might require a migration for existing datasets.

### PR DESCRIPTION
**Pull request by mcwhittemore**
Closes #160

### CODE REVIEW

**Comment by mcwhittemore** [comment]
@rclark can you give this a look?

**Comment by rclark** [comment]
Looks good. Just stylistically, I prefer to keep the `_` out of my JS objects -- could it be just `edits` or `editcount`?

**Comment by mcwhittemore** [comment]
changed to `editcount`. I'll merge and release once the tests pass.

**Comment by rclark** [comment]
@mcwhittemore I rebased on dyno v1.0.1 and fixed the test expectations for `editcount`. Ready to merge if you're happy with it!

**Pull request merged**
