### PR TITLE
Backoff on partial write failures

### LINKED ISSUE #170: Retry unprocessed items
Currently if cardboard makes a batch write request to DynamoDB, and unprocessed items are returned [cardboard does not attempt to retry those items](https://github.com/mapbox/cardboard/blob/master/lib/batch.js#L65-L77). This "error" may or may not be handled well downstream.

The untagged, master branch of dyno [contains new functions](https://github.com/mapbox/dyno/pull/119) intended to do this retrying for you. We should try it out here in cardboard.

cc @mcwhittemore

### PR DESCRIPTION
**Pull request by mcwhittemore**
Waiting on https://github.com/mapbox/dyno/pull/122

Closes #170

### CODE REVIEW

**Comment by mcwhittemore** [comment]
We might want to add a way for users to determine the number of retries as the default (10, the recommended number by AWS) takes a while.

**Comment by mcwhittemore** [comment]
Ready for review

**Comment by mcwhittemore** [comment]
@rclark as dyno@1.2.0 is merged, this is ready to review

**Comment by mcwhittemore** [comment]
ping @rclark

**Comment by rclark** [comment]
Looks good to me.

**Comment by mcwhittemore** [comment]
Merged and published as v2.2.0.

**Pull request merged**
